services:
  - type: web
    name: apollo-medical-portal
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEFAULT_TENANT_SLUG
        value: apollo-medical
      - key: NODE_OPTIONS
        value: "--max-old-space-size=460"
      - key: NEXTAUTH_URL
        value: https://apollo-medical-portal.onrender.com
      - key: NEXT_PUBLIC_BASE_URL
        value: https://apollo-medical-portal.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
